// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using cv_backend.Contexts;

#nullable disable

namespace sportsworld_backend.Migrations
{
    [DbContext(typeof(CVContext))]
    [Migration("20260314214138_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.14");

            modelBuilder.Entity("cv_backend.Models.Tenure", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Company_Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("End_Date")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Start_Date")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Work_Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Tenures");
                });
#pragma warning restore 612, 618
        }
    }
}
